name: Go CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: self-hosted
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21.5'
    
    - name: Build
      run: go build -v ./...
    
    - name: Test
      run: go test -v ./...
    
    - name: Build .env file
      run: echo "${{ secrets.PRO_ENV_FILE }}" > .env
    
    - name: Find and stop existing process
      run: |
        PID=$(pgrep -f "make run" || true)
        if [ -n "$PID" ]; then
          echo "Stopping existing process with PID $PID"
          kill $PID
          sleep 2
        else
          echo "No existing process found"
        fi
    
    - name: Start new process in the background
      run: nohup make run & disown
    
    - name: Notify Slack of success
      if: success()
      uses: slackapi/slack-github-action@v1.23.0
      with:
        payload: '{"text":"Deployment of commit ${{ github.sha }} to the production environment was successful."}'
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

    - name: Notify Slack of failure
      if: failure()
      uses: slackapi/slack-github-action@v1.23.0
      with:
        payload: '{"text":"Deployment of commit ${{ github.sha }} to the production environment failed."}'
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
