# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: self-hosted
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21.5'
    
    - name: Build
      run: go build -v ./...
    
    - name: Test
      run: go test -v ./...
    
    - name: Build .env file
      run: echo "${{ secrets.PRO_ENV_FILE }}" > .env
    
    - name: Find and stop existing process
      run: |
        PID=$(pgrep -f "make run")
        if [ -n "$PID" ]; then
          echo "Stopping existing process with PID $PID"
          kill $PID
          sleep 2
        else
          echo "No existing process found"
        fi
    
    - name: Start new Process in the background
      run: make run &
    
    - name: Check application status
      run: curl -I http://localhost:8080 || echo "Application is not running"
